import "./globals.css";
import type { Metadata } from "next";
import { Inter, Kanit, Mitr, Noto_Sans_Thai, IBM_Plex_Sans_Thai, Prompt, Itim, Krub } from "next/font/google";
import Navbar from "./Navbar";

const fonts = Prompt({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  style: "normal"
});

export const metadata: Metadata = {
  title: "House for Rent",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}